spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/sgae?useTimezone=true&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  server:
    port : 8081
    
name: prod-YAML
environment: production
servers: 
  - www.abc.com
  - www.xyz.com